apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: christians-apps
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: docker.io/christianclarke/hello_world:{{ .Values.env.version }}
          name: hello-world
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.service.port }}
            protocol: TCP
      automountServiceAccountToken: false
